spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://${KC_HOST:localhost}:${KC_PORT:8080}/auth/realms/rental_cars
      client:
        registration:
          rental-cars-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            scope: openid
            client-id: rental-cars-client
            client-secret: XMnpuDIckEkm7ozNBqUdDYX5cJqqwc3U
        provider:
          keycloak:
            issuer-uri: http://${KC_HOST:localhost}:${KC_PORT:8080}/auth/realms/rental_cars
  profiles:
    active: dev
  keycloak:
    auth-server-url: http://${KC_HOST:localhost}:${KC_PORT:8080}/auth
    realm: rental_cars
    resource: rental-cars-client
    credentials:
      secret: Nr4m2n42bpjsikbFUAk1j6QkuITkfHWF
    use-resource-role-mappings: true
    principal-attribute: preferred_username
    enabled: true

